# Generated by Django 5.2 on 2025-04-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('aid', models.AutoField(db_column='AID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('communityid', models.AutoField(db_column='CommunityID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('area', models.CharField(blank=True, db_column='Area', max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, db_column='Population', null=True)),
            ],
            options={
                'db_table': 'Communities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrimeRates',
            fields=[
                ('crimeid', models.AutoField(db_column='CrimeID', primary_key=True, serialize=False)),
                ('burglaryrate', models.DecimalField(blank=True, db_column='BurglaryRate', decimal_places=2, max_digits=5, null=True)),
                ('scamrate', models.DecimalField(blank=True, db_column='ScamRate', decimal_places=2, max_digits=5, null=True)),
                ('assaultrate', models.DecimalField(blank=True, db_column='AssaultRate', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Crime_Rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiningPlaces',
            fields=[
                ('diningid', models.AutoField(db_column='DiningID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('ratings', models.DecimalField(blank=True, db_column='Ratings', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'Dining_Places',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EducationInstitutions',
            fields=[
                ('institutionid', models.AutoField(db_column='InstitutionID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('noofstudents', models.IntegerField(blank=True, db_column='NoOfStudents', null=True)),
                ('communityid', models.ForeignKey(db_column='CommunityID', on_delete=django.db.models.deletion.CASCADE, to='guides.communities')),
            ],
            options={
                'db_table': 'Education_Institutions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Superstores',
            fields=[
                ('superstoreid', models.AutoField(db_column='SuperstoreID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Superstores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('transitid', models.AutoField(db_column='TransitID', primary_key=True, serialize=False)),
                ('transitno', models.CharField(blank=True, db_column='TransitNo', max_length=50, null=True)),
                ('route', models.CharField(blank=True, db_column='Route', max_length=100, null=True)),
                ('endstop', models.CharField(blank=True, db_column='EndStop', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Transit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('Email', models.EmailField(db_column='Email', max_length=50)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('institutionid', models.OneToOneField(db_column='InstitutionID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guides.educationinstitutions')),
            ],
            options={
                'db_table': 'Schools',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UniversitiesColleges',
            fields=[
                ('institutionid', models.OneToOneField(db_column='InstitutionID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='guides.educationinstitutions')),
            ],
            options={
                'db_table': 'Universities_Colleges',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HealthcareFacilities',
            fields=[
                ('facilityid', models.AutoField(db_column='FacilityID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('communityid', models.ForeignKey(db_column='CommunityID', on_delete=django.db.models.deletion.CASCADE, to='guides.communities')),
            ],
            options={
                'db_table': 'Healthcare_Facilities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentalPlaces',
            fields=[
                ('rentalid', models.AutoField(db_column='RentalID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('rent', models.DecimalField(blank=True, db_column='Rent', decimal_places=2, max_digits=10, null=True)),
                ('streetno', models.CharField(blank=True, db_column='StreetNo', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True)),
                ('communityid', models.ForeignKey(db_column='CommunityID', on_delete=django.db.models.deletion.CASCADE, to='guides.communities')),
            ],
            options={
                'db_table': 'Rental_Places',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserQueries',
            fields=[
                ('queryid', models.AutoField(db_column='QueryID', primary_key=True, serialize=False)),
                ('querytext', models.CharField(blank=True, db_column='QueryText', max_length=500, null=True)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
                ('uid', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='guides.users')),
            ],
            options={
                'db_table': 'User_Queries',
                'managed': True,
            },
        ),
    ]
