services:
  - type: web
    name: calgary-guide-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn CPSC471CalgaryGuidesystem.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CPSC471CalgaryGuidesystem.settings
      - key: PYTHON_VERSION
        value: 3.12
